### ISSUE TITLE
Connection detail pages not displaying correctly

### ISSUE THREAD

**Issue by marpa** [clas-web/unc-charlotte-connections-theme#3]
Connection detail pages not displaying correctly with latest versions of VTT and unc charlotte variations plugin

**Comment by marpa** [comment]
Here is link on preprod, see:
https://clas-pages-test.uncc.edu/connections/connection/oscar-de-la-torre-cueva/

**Comment by atrus1701** [comment]
8dc64a3349650700eedee229e8bdc2b538459e84
