### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by clas-web** [clas-web/unc-charlotte-connections-theme#4]
There are a number of minor CSS issues.
Connection Links
The box containing connection links is missing right border, see:
https://pages.uncc.edu/connections/department/africana-studies/

Related research "more" link sometimes outside of related box, see:
https://pages.uncc.edu/connections/department/geography-and-earth-sciences/

**Comment by atrus1701** [comment]
799bf00a2b4b14fc9b99659166fd5de7e0d14a97
